language: php
services:
    - postgresql

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
php:
    - 7.0
    - 7.1

before_install: 
    - travis_retry composer self-update

install: 
    - psql -c 'create database zutto_test;' -U postgres
    - cp .travis.env .env
    - travis_retry composer install --dev --no-interaction 
    - composer show 
    - php artisan passport:keys

script: 
    - composer cs-check
    - composer test 

after_failure: 
    - cat storage/logs/lumen.log 

# after_success: # one day...
after_script:
    - travis_retry php vendor/bin/coveralls

notifications:
    email: false
    irc: "ircs://irc.yasashiisyndicate.org:6697/#zutto"

